name: bitcoin-ts-1
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - altair=6.0.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py314h5a2d7ad_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py314h680f03e_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py314he701e3d_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h5a2d7ad_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.2=py314hd8ed1ab_100
  - debugpy=1.8.19=py314hb98de8c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=22.0.0=h5f2f476_6_cuda
  - libarrow-acero=22.0.0=h7d8d6a5_6_cuda
  - libarrow-compute=22.0.0=h2db994a_6_cuda
  - libarrow-dataset=22.0.0=h7d8d6a5_6_cuda
  - libarrow-substrait=22.0.0=hf865cc0_6_cuda
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libparquet=22.0.0=h7051d1f_6_cuda
  - libpng=1.6.53=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.2=hb980946_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_454
  - narwhals=2.14.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.5.1=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314hd8fd7ce_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pillow=12.0.0=py314h61b30b5_2
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py314hc5dbbe4_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py314h86ab7b2_0
  - pyarrow-core=22.0.0=py314hc631f2f_0_cuda
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.14.2=h4b44e0e_100_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.14.2=h4df99d1_100
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py314h8f8f202_1
  - pywinpty=2.0.15=py314h51f0985_1
  - pyyaml=6.0.3=pyh7db6752_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py314h9f07db2_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - streamlit=1.52.2=pyhd8ed1ab_0
  - tbb=2022.3.0=hd094cb3_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.4=py314h5a2d7ad_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - watchdog=6.0.0=py314h86ab7b2_2
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - cmdstanpy==1.3.0
      - contourpy==1.3.3
      - curl-cffi==0.14.0
      - cycler==0.12.1
      - fonttools==4.61.1
      - frozendict==2.4.7
      - holidays==0.87
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - multitasking==0.0.12
      - numpy==2.3.5
      - patsy==1.0.2
      - peewee==3.18.3
      - prophet==1.2.1
      - protobuf==6.33.2
      - pycparser==2.23
      - pyparsing==3.2.5
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - stanio==0.5.1
      - statsmodels==0.14.6
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - websockets==15.0.1
      - yfinance==0.2.66
prefix: C:\Users\U1\miniconda3\envs\bitcoin-ts-1
