name: bitcoin-ts-1
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.2.0=py310h458dff3_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.19=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - frozendict=2.4.7=py310h29418f3_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.1=hf5d6505_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lxml=6.0.2=py310h095aac5_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - multitasking=0.0.12=pyhd8ed1ab_0
  - narwhals=2.14.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.2.6=py310h4987827_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_2
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - peewee=3.18.3=py310h4cd0a36_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.0=py310h1637853_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rpds-py=0.30.0=py310h034784e_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py310h8f3aa81_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py310h29418f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - yfinance=0.2.57=pyhd8ed1ab_0
  - zeromq=4.3.5=h5bddc39_9
  - zstd=1.5.7=h534d264_6
  - pip:
      - altair==6.0.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - click==8.3.1
      - cmdstanpy==1.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.61.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - holidays==0.87
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - pillow==12.0.0
      - prophet==1.2.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - pyparsing==3.3.1
      - smmap==5.0.2
      - stanio==0.5.1
      - streamlit==1.52.2
      - tenacity==9.1.2
      - toml==0.10.2
      - tqdm==4.67.1
      - watchdog==6.0.0
prefix: C:\Users\U1\miniconda3\envs\bitcoin-ts-1
